version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: proyecto-node-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=proyecto_node
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: ["sh", "-c", "wait-for-it db:3306 -- npm run dev"] 
    #command: ["sh", "-c", "wait-for-it db:3306 -- nodemon --legacy-watch index.js"] 

  db:
    image: mysql:8
    container_name: proyecto-node-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: proyecto_node
    ports:
      - "4306:3306"
    volumes:
      - ./db:/var/lib/mysql
